spring:
  data:
    auth-service: "http://localhost:8083"
    api-handler-service: "http://localhost:8082"
    jwt:
      secret: "8w9U7eupsVcokibCDUjO59xuTkl9XJvtMJnx0O7ysqmlmYROYHm88YASpGOsPKFP"

server:
  uri: "http://localhost:8080/"
  port: 8080