spring:
  data:
    auth-service: "http://auth-service"
    api-handler-service: "http://api-handler-service"
    jwt:
      secret: "8w9U7eupsVcokibCDUjO59xuTkl9XJvtMJnx0O7ysqmlmYROYHm88YASpGOsPKFP"

server:
  port: 8080