apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 32002