apiVersion: v1
kind: Service
metadata:
  name: api-handler-service
spec:
  selector:
    app: api-handler-service
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 32001