apiVersion: v1
kind: Service
metadata:
  name: shortlink-service
spec:
  selector:
    app: shortlink-service
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 32000