apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: wwerloshh/my-own-repo:gateway-service-v1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          envFrom:
            - configMapRef:
                name: shared-config
  selector:
    matchLabels:
      app: gateway-service
