apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 32003