spring:
  application:
    name: api-handler-service
  data:
    redis:
      host: redis
      port: 6379
      repositories:
        enabled: false
shortlink:
  service:
    url: http://shortlink-service

