spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shortened_urls
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
server:
  port: 8082
