spring:
  application:
    name: api-handler-service
  datasource:
    url: jdbc:postgresql://postgres:5432/shortened_urls
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: redis
      port: 6379
      repositories:
        enabled: false
shortlink:
  service:
    url: http://shortlink-service:8081
server:
  port: 8082

