spring:
  application:
    name: api-handler-service
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
shortlink:
  service:
    url: http://localhost:8081

